/* Generated By:JavaCC: Do not edit this line. LugosiConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LugosiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int VAR = 8;
  /** RegularExpression Id. */
  int PONTOEVIRGULA = 9;
  /** RegularExpression Id. */
  int INT = 10;
  /** RegularExpression Id. */
  int BOOL = 11;
  /** RegularExpression Id. */
  int DOISPONTOSIGUAL = 12;
  /** RegularExpression Id. */
  int APARENTESES = 13;
  /** RegularExpression Id. */
  int FPARENTESES = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int WHILE = 16;
  /** RegularExpression Id. */
  int DO = 17;
  /** RegularExpression Id. */
  int RETURN = 18;
  /** RegularExpression Id. */
  int PRINT = 19;
  /** RegularExpression Id. */
  int TRUE = 20;
  /** RegularExpression Id. */
  int FALSE = 21;
  /** RegularExpression Id. */
  int SUM = 22;
  /** RegularExpression Id. */
  int SUB = 23;
  /** RegularExpression Id. */
  int MULT = 24;
  /** RegularExpression Id. */
  int DIV = 25;
  /** RegularExpression Id. */
  int AND = 26;
  /** RegularExpression Id. */
  int OR = 27;
  /** RegularExpression Id. */
  int MENOR = 28;
  /** RegularExpression Id. */
  int MAIOR = 29;
  /** RegularExpression Id. */
  int IGUAL = 30;
  /** RegularExpression Id. */
  int VIRGULA = 31;
  /** RegularExpression Id. */
  int FUNCAO = 32;
  /** RegularExpression Id. */
  int NUM = 33;
  /** RegularExpression Id. */
  int ID = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"var\"",
    "\";\"",
    "\"int\"",
    "\"bool\"",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\"if\"",
    "\"while\"",
    "\"do\"",
    "\"return\"",
    "\"print\"",
    "\"true\"",
    "\"false\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\",\"",
    "\"function\"",
    "<NUM>",
    "<ID>",
  };

}
